name: Build and Deploy ASP.NET Core to GitHub Pages

on:
  push:
    branches: [ dev ] # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # 设置GitHub Pages权限
    permissions:
      contents: read
      pages: write
      id-token: write
    
    # 确保只有一个部署任务同时运行
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./src/code/testcicd/testcicd.sln
      
    - name: Build project
      run: dotnet build ./src/code/testcicd/testcicd.sln -c Release --no-restore
      
    - name: Publish app for web deployment
      run: dotnet publish ./src/code/testcicd/testcicd.sln -c Release -o ./publish --no-build
      
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: './publish'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # 可选：为本地部署准备文件下载
  create-local-deployment:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Build self-contained app for Linux
      run: |
        dotnet restore ./src/code/testcicd/testcicd.sln
        dotnet publish ./src/code/testcicd/testcicd.sln -c Release -o ./local-deploy \
          --self-contained true -r linux-x64 --no-restore
        
    - name: Archive local deployment files
      uses: actions/upload-artifact@v4
      with:
        name: testcicd-linux-deployment
        path: ./local-deploy/
        retention-days: 30
